Use Async Output Where Possible

diff --git a/.github/actions/check-release/action.yml b/.github/actions/check-release/action.yml
--- a/.github/actions/check-release/action.yml
+++ b/.github/actions/check-release/action.yml
@@ -33,10 +33,10 @@ runs:
         fi
 
         # Install Jupyter Releaser from git unless we are testing Releaser itself
-        export RH_REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f 2)
-        echo "repo name: ${RH_REPO_NAME}"
-        if [ ${RH_REPO_NAME} !=  "jupyter_releaser" ]; then
-           pip install git+https://github.com/jupyter-server/jupyter_releaser.git
+        if ! command -v jupyter-releaser &> /dev/null
+        then
+            echo "COMMAND could not be found"
+            exit
         fi
 
         export RH_IS_CHECK_RELEASE=true
